# Generated by Django 5.1.15 on 2026-04-18 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edizione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True, verbose_name='Numero edizione')),
                ('titolo', models.CharField(blank=True, max_length=120)),
                ('data_inizio', models.DateField()),
                ('data_fine', models.DateField()),
                ('descrizione', models.TextField(blank=True)),
                ('locandina', models.ImageField(blank=True, null=True, upload_to='edizioni/')),
                ('is_corrente', models.BooleanField(default=False, help_text='Solo una edizione può essere quella corrente.', verbose_name='Edizione corrente')),
                ('biglietti_url', models.URLField(blank=True, verbose_name='URL biglietti')),
            ],
            options={
                'verbose_name': 'Edizione',
                'verbose_name_plural': 'Edizioni',
                'ordering': ['-numero'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domanda', models.CharField(max_length=200)),
                ('risposta', models.TextField()),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('pubblicata', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['ordine', 'domanda'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('indirizzo', models.CharField(max_length=200)),
                ('citta', models.CharField(max_length=80, verbose_name='Città')),
                ('provincia', models.CharField(blank=True, max_length=2)),
                ('cap', models.CharField(blank=True, max_length=10, verbose_name='CAP')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitudine')),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitudine')),
                ('google_maps_url', models.URLField(blank=True)),
                ('descrizione', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Venue',
                'verbose_name_plural': 'Venue',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='band/')),
                ('sito_web', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('spotify', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('giorno', models.DateField(blank=True, null=True)),
                ('orario', models.TimeField(blank=True, null=True)),
                ('headliner', models.BooleanField(default=False)),
                ('ordine', models.PositiveIntegerField(default=0, help_text='Ordine di visualizzazione in line-up')),
                ('edizione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='band', to='core.edizione')),
            ],
            options={
                'verbose_name': 'Band',
                'verbose_name_plural': 'Band',
                'ordering': ['-headliner', 'ordine', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='edizione',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='edizioni', to='core.venue'),
        ),
    ]
