# Generated by Django 5.2.13 on 2026-04-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='visibile',
            field=models.BooleanField(default=True, verbose_name='Visibile sul sito'),
        ),
    ]
